name: Build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-and-build:
    runs-on: macos-15

    steps:
      - uses: actions/checkout@v7

      - name: Test and build
        run: ./build.sh
